pippo-core/src/main/java/ro/fortsoft/pippo/core/controller/Body.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/controller/DefaultControllerHandler.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/controller/Form.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/crudng/CrudNgApiController.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/crudng/CrudNgApplication.java
I'm open to suggestions on names for the annotations.
`@Form` -> build entity from request parameters
`@Body` -> body entity from request body
`@Param` -> named request parameter
`@ParamPattern` -> currently used for handling deserialization of dates
Maybe those are good enough but perhaps...
- `@Param` should be `@Named` ?
- `@ParamPattern` should be `@Pattern` ?
=> Allow entities to be automatically instantiated using optional controller annotations

pippo-core/src/main/java/ro/fortsoft/pippo/core/PippoConstants.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/WebServerSettings.java, pippo-jetty/src/main/java/ro/fortsoft/pippo/jetty/JettyServer.java
This PR exposes all WebServerSettings to the `application.properties` file.  It also slightly revises the serving of external files.  External files are now served on a subpath of the context instead of co-mingling Pippo & external files directly on the context path. (i.e.  serve external files from `/context/ext` not `/context`).  The external files path is configurable via the API or `application.properties`.
Serving from multiple sources on the same exact path can create problems for other `WebServer` implementations.
=> Expose all WebServerSettings to application.properties and add external files path

pippo-core/src/main/java/ro/fortsoft/pippo/core/DefaultErrorHandler.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/Error.java
Not all content-type engines are able to serialize & deserialize arbitrary Objects.
For example, JAXB can not natively serialize a collection.  To avoid internal
Pippo errors with the ContentTypeEngines, Pippo should use a concrete class
to represent an error.
=> Implement a concrete Error class for passing to ContentTypeEngines

pippo-core/src/main/java/ro/fortsoft/pippo/core/route/DefaultRouter.java, pippo-core/src/test/java/ro/fortsoft/pippo/core/DefaultRouterTest.java
Despite the availability of API in Router to add a handler for any HttpMethod, `DefaultRouter` rejects routes if they do not specify one of HEAD, GET, PATCH, POST, PUT, or DELETE.
=> Relax the validation of HTTP methods on route registration

pippo-core/src/main/java/ro/fortsoft/pippo/core/DefaultRequestFactory.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/DefaultResponseFactory.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/PippoFilter.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/Request.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/RequestFactory.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/Response.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/ResponseFactory.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/route/RouteHandler.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/CustomHandler.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/CustomRequest.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/CustomRequestFactory.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/CustomResponse.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/CustomResponseFactory.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/SimpleApplication.java, pippo-demo/src/main/resources/META-INF/services/ro.fortsoft.pippo.core.RequestFactory, pippo-demo/src/main/resources/META-INF/services/ro.fortsoft.pippo.core.ResponseFactory
This allows consumers of Pippo to implement higher level RouteHandlers which contain domain-specific logic such as object serialization/deserialization, etc.
=> RFC: Add factories for Request and Response

pippo-core/src/main/java/ro/fortsoft/pippo/core/DefaultErrorHandler.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/HttpConstants.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/Response.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/route/ClasspathResourceHandler.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/SimpleApplication.java, pippo-demo/src/main/java/ro/fortsoft/pippo/demo/crudng/CrudNgApiController.java
The status code methods are now setters which follow the builder pattern used by the header, cookie, and content type methods.
Also ensure we are not attempting to modify the response after it has been committed.
This is related to issue #66.
=> Separate the status code convenience methods from the commit action

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/Response.java, pippo-core/src/main/java/ro/pippo/core/route/ClasspathResourceHandler.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/pippo/core/route/FileResourceHandler.java, pippo-core/src/main/java/ro/pippo/core/route/Router.java, pippo-core/src/main/java/ro/pippo/core/route/StaticResourceHandler.java, pippo-demo/pippo-demo-basic/src/main/java/ro/pippo/demo/basic/BasicApplication.java
Now are two implementations available `ClasspathResourceHandler` (serves classpath resources) and `FileResourceHandler` (serves file resources)
I improved pippo-demo-basic with a new route:
```java
// send files from a local folder (try a request like 'src/main/java/ro/pippo/demo/basic/BasicApplication.java')
GET(new FileResourceHandler("/src", "src"));
```
What you think?
=> add StaticResourceHandle

pippo-core/src/main/java/ro/pippo/core/route/ClasspathResourceHandler.java, pippo-core/src/main/java/ro/pippo/core/route/FileResourceHandler.java, pippo-core/src/main/java/ro/pippo/core/route/StaticResourceHandler.java
The file resource handler could not serve anything outside `user.dir` and it should accept a File argument.
=> Improvements & fixes to the FileResourceHandler

pippo-core/src/main/java/ro/pippo/core/DefaultSessionFactory.java
If a servlet session is not created we can not have a DefaultSession.
=> Fix DefaultSessionFactory

pippo-core/src/main/java/ro/pippo/core/Flash.java
I'm not sure we need more than 4 levels of Flash messages; Flash is not the same as logging.
I also adjusted `isLevel()` which I think had a bug.
=> Simplified Flash implementation by eliminating levels

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouteContext.java, pippo-core/src/main/java/ro/pippo/core/route/Route.java, pippo-demo/pippo-demo-basic/src/main/java/ro/pippo/demo/basic/BasicApplication.java
Once your app gets large enough, logging by method and uri pattern is insufficient.
This PR adds the builder pattern to route registration with the first supported value as `Route` *name*.
=> Add support for naming routes to bring meaningful context to logs

pippo-core/src/main/java/ro/pippo/core/DefaultErrorHandler.java, pippo-core/src/main/java/ro/pippo/core/ErrorHandler.java, pippo-core/src/main/java/ro/pippo/core/ExceptionHandler.java, pippo-core/src/main/java/ro/pippo/core/PippoFilter.java, pippo-demo/pippo-demo-basic/src/main/java/ro/pippo/demo/basic/BasicApplication.java
This is a light-weight alternative to implementing a full `ErrorHandler` or subclassing `DefaultErrorHandler`.
The `ErrorHandler` is also an `ExceptionHandler` so if no registered `ExceptionHandler` is found for the exception, then the `ErrorHandler` implementation is used.  But the `ErrorHandler` is more than an `ExceptionHandler` because it is a registry of `ExceptionHandler` instances and it can generate status-code based results.
This is an important piece when integrating custom or library exceptions into a Pippo application.
=> Allow registration of custom ExceptionHandlers

maven-archetypes/quickstart/pom.xml, maven-archetypes/quickstart/src/main/resources/META-INF/maven/archetype-metadata.xml, maven-archetypes/quickstart/src/main/resources/archetype-resources/pom.xml, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/java/PippoApplication.java, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/java/PippoLauncher.java, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/conf/application.properties, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/conf/messages.properties, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/conf/messages_de.properties, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/conf/messages_es.properties, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/conf/messages_fr.properties, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/conf/messages_ro.properties, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/conf/messages_ru.properties, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/simplelogger.properties, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/resources/templates/hello.ftl, maven-archetypes/quickstart/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/web.xml
I will create a new section in pippo-site to explain how to use it.
Steps:
- install `pippo-quickstart` archetype on your computer (**OPTIONAL** - the archetype will be available soon on Maven Central Repository):
```
cd <PIPPO_HOME>/maven-archetypes/quickstart
mvn install
```
- create your quickstart project:
```
mvn archetype:generate \
-DarchetypeGroupId=ro.pippo \
-DarchetypeArtifactId=pippo-quickstart \
-DarchetypeVersion=0.5.0-SNAPSHOT \
-DgroupId=com.mycompany \
-DartifactId=myproject
```
- run your application from command line:
```
cd myproject
mvn compile exec:java
```
now your application is available at `http://localhost:8338`
If you want to create the `war` file of your application then you must run `mvn -Pwar package`. 
`-Pwar` excludes the libraries of the embedded web …
=> maven quickstart archetype #126

CHANGELOG.md, pippo-controller/src/main/java/ro/pippo/controller/DefaultControllerHandler.java, pippo-core/src/main/java/ro/pippo/core/ParameterValue.java, pippo-core/src/main/java/ro/pippo/core/Request.java, pippo-core/src/test/java/ro/pippo/core/ParameterValueTest.java, pippo-demo/pippo-demo-controller/src/main/java/ro/pippo/demo/controller/CollectionsController.java, pippo-demo/pippo-demo-controller/src/main/java/ro/pippo/demo/controller/ControllerApplication.java, pippo-demo/pippo-demo-controller/src/main/resources/templates/collections.ftl
This adds support for things like `List`, `Set`, and `TreeSet`.  The implementation covers Controllers and direct ParameterValue access from `RouteHandler`.  To compliment this feature, the `Request` will now recognize and assemble indexed-parameters.
=> Add support for 1-dimensional collections

CHANGELOG.md, pippo-core/src/main/java/ro/pippo/core/PippoFilter.java, pippo-core/src/main/java/ro/pippo/core/PippoServlet.java, pippo-core/src/main/java/ro/pippo/core/Request.java, pippo-core/src/main/java/ro/pippo/core/route/CSRFHandler.java, pippo-demo/pippo-demo-controller/src/main/java/ro/pippo/demo/controller/CollectionsController.java, pippo-demo/pippo-demo-controller/src/main/java/ro/pippo/demo/controller/ControllerApplication.java, pippo-demo/pippo-demo-controller/src/main/resources/templates/collections.ftl
This is the same useful behavior found in Rails and Django.  It allows for applying a more RESTful design to standard form processing.  To use it, specify a hidden input field named `_method` with a value of the preferred http method (e.g. `PATCH`, `PUT`, `DELETE`, etc).  Pippo will automatically route the POSTed request to the preferred handler.  The Collections controller example has been updated to use `PUT` as a demonstration.
=> Allow html forms to specify _method which overrides the servlet method

pippo-jetty/src/main/java/ro/pippo/jetty/JettySettings.java
If not configured, use jetty-9 default values for threads.
=> Jetty-9 default values

pippo-core/src/main/java/ro/pippo/core/route/DefaultRouteContext.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/pippo/core/route/Route.java, pippo-core/src/main/java/ro/pippo/core/route/RouteContext.java, pippo-core/src/main/java/ro/pippo/core/route/Router.java, pippo-demo/pippo-demo-ajax/src/main/java/ro/pippo/demo/ajax/AjaxApplication.java
I try to implements the idea from the comment https://github.com/decebals/pippo/pull/99#issuecomment-77233748
In few words I can add a route (in an hypothetical blog application) with:
```java
GET("/blogs/{year}/{month}/{day}/{title}", (routeContext) -> { routeContext.render("myTemplate)});
```
It's hard to create the reverse routing using the `uriPattern`:
```java
Map<String, Object> parameters = ...
routeContext.uriFor("/blogs/{year}/{month}/{day}/{title}", parameters);
```
Now you can add a `name` for a route and to use this name when you build the URL(reverse routing) to that route:
```java
GET("/blogs/{year}/{month}/{day}/{title}", (routeContext) -> { routeContext.render("myTemplate)}).named("blog");
```
The new cod becomes:
```java
Map<String, Object> parameters = ... …
```
=> add route name as first criterion in urlFor

CHANGELOG.md, pippo-core/src/main/java/ro/pippo/core/ParameterValue.java, pippo-core/src/test/java/ro/pippo/core/ParameterValueTest.java
This PR adds improved support for array extraction from ParameterValue.
```java
Arrays.equals(new int [] {1,2,3,4,5}, new ParameterValue("1|2|3|4|5").to(int[].class));
Arrays.equals(new int [] {1,2,3,4,5}, new ParameterValue("1,2,3,4,5").to(int[].class));
```
=> Improve array support in ParameterValue

pippo-gson/pom.xml, pippo-gson/src/main/java/ro/pippo/gson/GsonEngine.java, pippo-gson/src/main/test/ro/pippo/gson/GsonEngineTest.java
This PR specifies ISO8601 date & time formatters for the Gson engine.  The current implementation leaves date & time serialization to a locally formatted , non-standard string.  This proposal uses a standard date/time interchange format.
https://en.wikipedia.org/wiki/ISO_8601
=> Serialize and deserialize date, time, and datetime using ISO8601 in Gson

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-demo/pom.xml, pippo-jaxb/pom.xml, pippo-jaxb/src/main/java/ro/pippo/jaxb/JaxbEngine.java, pippo-jaxb/src/main/java/ro/pippo/jaxb/JaxbInitializer.java, pippo-jaxb/src/main/resources/META-INF/services/ro.pippo.core.ContentTypeEngine, pippo-jaxb/src/main/resources/pippo.properties, pom.xml
Unfortunately by having the JAXB engine set by the core it is not possible to replace it using our ServiceLoader/Initializer design.
We could add special cases to ContentTypeEngine registration - ick - or we could split the JAXB engine into a separate module that you must deliberately choose - I think this is better.
=> Split JAXB engine into a separate module

pippo-core/src/main/java/ro/pippo/core/route/WebjarsResourceHandler.java, pippo-demo/pippo-demo-crud/src/main/resources/templates/base.ftl, pippo-demo/pippo-demo-crudng/src/main/resources/templates/base.ftl
This PR changes the Webjars handler version aliasing introduced in #180 to support implied request resource path version aliases like `jquery/` instead of requiring `jquery/current/` paths.
This means the first path segment (*artifactId*) will be substituted at runtime with *artifactId/version/* (e.g. `jquery/1.11.1/`) UNLESS the request resource path already starts with *artifactId/version/* (e.g. `jquery/1.11.1/`).
=> Change Webjars path aliasing to only use the artifactId

pippo-core/src/main/java/ro/pippo/core/ContentTypeEngines.java, pippo-core/src/main/java/ro/pippo/core/Request.java, pippo-core/src/main/java/ro/pippo/core/util/StringUtils.java, pippo-demo/pippo-demo-basic/pom.xml, pippo-demo/pippo-demo-basic/src/main/java/ro/pippo/demo/basic/BasicApplication.java
This PR allows specification of the `Accept-Type` on the `Request` path.
http://localhost:8338/contact
http://localhost:8338/contact.json
http://localhost:8338/contact.xml
http://localhost:8338/contact.yaml
The path suffix is matched against the trailing pseudo-suffix of the registered `ContentTypeEngine`.
e.g. `application/json` = `json`
e.g. `application/x-yaml` = `yaml`
```java
GET("/contact(\\.(json|xml|yaml))?", new RouteHandler() {
@Override
public void handle(RouteContext routeContext) {
Contact contact = new Contact()
.setId(12345)
.setName("John")
.setPhone("0733434435")
.setAddress("Sunflower Street, No. 6");
routeContext.xml().negotiateContentType().send(contact);
}
});
```
Aside from the verbose route path specification, the behavior is transparent to the end-user.  I have an …
=> Allow specification of Accept-Type by appending a registered suffix to the request path

pippo-core/src/main/java/ro/pippo/core/route/WebjarsResourceHandler.java
Found a nasty bug in the new webjars aliasing.
Example:
`${webjarsAt('foundation/js/foundation/foundation.alert.js')}`
will resolve to:
`/webjars/foundation/5.5.2/js/foundation/5.5.2/foundation.alert.js`
Note the double version substitution.  Iz bad.
This PR fixes that.  *I wouldn't be opposed to a quick 0.6.1.*
**Also.**
It should also be noted that our webjars aliasing may not work when the same version of a webjar is rebuilt with a `-n` suffix.
For example, font-awesome 4.3.0-1 is a rebuild of font-awesome 4.3.0 with an erroneous Maven dependency removed.  Inside the 4.3.0-1 jar the paths are still "4.3.0".  If we are brave we could strip the `-n` suffix but I honestly don't know if that will cause more harm than good.
=> Fix alias substitution in webjars paths

pippo-core/src/main/java/ro/pippo/core/util/ClasspathUtils.java, pippo-demo/pippo-demo-basic/pom.xml, pippo-jackson/pom.xml, pippo-jackson/src/main/java/ro/pippo/jackson/JacksonBaseEngine.java, pippo-jackson/src/main/java/ro/pippo/jackson/JacksonInitializer.java, pippo-jackson/src/main/java/ro/pippo/jackson/JacksonJsonEngine.java, pippo-jackson/src/main/java/ro/pippo/jackson/JacksonXmlEngine.java, pippo-jackson/src/main/java/ro/pippo/jackson/JacksonYamlEngine.java, pippo-jackson/src/main/resources/META-INF/services/ro.pippo.core.ContentTypeEngine, pippo-jackson/src/test/java/ro/pippo/jackson/JacksonBaseEngineTest.java, pippo-jackson/src/test/java/ro/pippo/jackson/JacksonJsonEngineTest.java, pippo-jackson/src/test/java/ro/pippo/jackson/JacksonXmlEngineTest.java, pippo-jackson/src/test/java/ro/pippo/jackson/JacksonYamlEngineTest.java
Jackson supports reading/writing multiple formats using the same set of annotations.  In many cases you may not need any data annotations at all to read/write.
This PR refactors the Jackson integration to register Json, Xml, and Yaml engines.  It's a one-stop dependency for all three content types.
What do you think of this approach?
=> Register Json, Xml, and Yaml engines with pippo-jackson

pippo-core/src/test/java/ro/pippo/core/DefaultRouterTest.java, pippo-core/src/test/java/ro/pippo/core/ParameterValueTest.java, pippo-core/src/test/java/ro/pippo/core/PathRegexBuilderTest.java
I don't like the idea of static import in general but I think that we must do a concession for the test classes.
In pippo test classes we extended Assert class only to force the import but I think that it's bad for readability.
I used InteliiJ Idea so I used [this](http://stackoverflow.com/questions/5107023/add-favorite-methods-to-static-import-in-intellij) recommendation in my projects.
=> remove "extends Assert" from each existent Test class

pippo-freemarker/src/main/java/ro/pippo/freemarker/FreemarkerTemplateEngine.java, pippo-groovy/src/main/java/ro/pippo/groovy/GroovyTemplateEngine.java, pippo-jade/src/main/java/ro/pippo/jade/JadeTemplateEngine.java, pippo-pebble/src/main/java/ro/pippo/pebble/PebbleTemplateEngine.java, pippo-trimou/src/main/java/ro/pippo/trimou/TrimouTemplateEngine.java, pippo-velocity/src/main/java/ro/pippo/velocity/VelocityTemplateEngine.java
Implementation based on [this](https://github.com/decebals/pippo/pull/212#issuecomment-136359578) comment.
I have a updated pippo-demo-template on pipe:
```java
public class PebbleDemo {
public static void main(String[] args) {
// .peb is the default file extension
//        Pippo pippo = new Pippo(new TemplateApplication(new PebbleTemplateEngine(), "pebble/hello"));
Pippo pippo = new Pippo(new TemplateApplication(new MyPebbleTemplateEngine(), "pebble/hello"));
pippo.start();
}
public static class MyPebbleTemplateEngine extends PebbleTemplateEngine {
@Override
protected void init(PebbleEngine engine) {
engine.addExtension(new AbstractExtension() {
@Override
public Map<String, Filter> getFilters() {
Map<String, Filter> filters = new HashMap<>();
filters.put("myupper", new MyUpperFilter()); …
```
=> make TemplateEngine configurable (see #211), reloaded

CHANGELOG.md, pippo-core/src/main/java/ro/pippo/core/route/CSRFHandler.java, pippo-core/src/main/java/ro/pippo/core/util/StringUtils.java
The CSRF guard skips token validation for POST requests that are sent with charsets.
e.g. `Content-Type: application/x-www-form-urlencoded; charset=utf8`.
This is no bueno.  :-1:
=> Fix CSRF guard failure on content-types with specified charsets

CHANGELOG.md, pippo-core/src/main/java/ro/pippo/core/Response.java
Pippo is an abstraction and convenience layer for the servlet API.  If you
need to implement custom streaming you can not use any of the Response
API when setting up headers, etc.  This change allows you to configure the
Response, as you normally would, and then obtain the raw output stream for
custom response streaming.
=> Add method to finalize the Response and return the raw output stream

CHANGELOG.md, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/test/java/ro/pippo/core/DefaultRouterTest.java
Add support for the `:alnum:`, `:alpha:`, `:ascii:`, `:digit:`, and `:xdigit:` POSIX character classes in URL path parameters.  These values are substituted for their Java equivalent when the Route PatternBinding is created by DefaultRouter.
Using the Java equivalent syntax *directly* creates complications with the existing route parameter matching expression due to nesting of curly braces.  This alternative is less invasive.
=> Allow use of UTF-8 in path parameter expressions

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-fastjson/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-fastjson/src/main/resources/pippo.properties, pippo-freemarker/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-freemarker/src/main/resources/pippo.properties, pippo-groovy/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-groovy/src/main/resources/pippo.properties, pippo-gson/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-gson/src/main/resources/pippo.properties, pippo-jackson/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-jackson/src/main/resources/pippo.properties, pippo-jade/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-jade/src/main/resources/pippo.properties, pippo-jaxb/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-jaxb/src/main/resources/pippo.properties, pippo-pebble/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-pebble/src/main/resources/pippo.properties, pippo-snakeyaml/src/main/resources/pippo.properties, pippo-snakeyaml/src/main/resources/services/ro.pippo.core.Initializer, pippo-trimou/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-trimou/src/main/resources/pippo.properties, pippo-velocity/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-velocity/src/main/resources/pippo.properties, pippo-xstream/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-xstream/src/main/resources/pippo.properties
The idea is to simplify the `Initializer` implementation and to use an unitary services/extensions mechanism in Pippo (we already use java `ServiceLoader` mechanism via `ServiceLocator` for `ContentTypeEngine`, `TemplateEngine`).
=> use standard java service loader mechanism via ServiceLocator and remove pippo.properties files

pippo-controller/src/main/java/ro/pippo/controller/ControllerApplication.java, pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/pippo/core/route/Route.java, pippo-core/src/main/java/ro/pippo/core/route/RouteDispatcher.java, pippo-core/src/main/java/ro/pippo/core/route/Router.java, pippo-core/src/test/java/ro/pippo/core/DefaultRouterTest.java
This pull request comes with three changes:
- Change order of requestMethod, uriPattern (Route constructor) according to #138
- Change order of requestMethod, uriPattern (Route.findRoutes)
- Add static factory methods for GET, POST, ... in Route class
I think that code is more clear. The signature for the Route constructor was changed but I think that it's not a big problem because nobody uses the Route constructor directly.
I will add some javadoc if you are OK with these modifications.
=> Cosmetics for Route class

pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/pippo/core/route/ResourceHandler.java, pippo-core/src/main/java/ro/pippo/core/route/UrlResourceHandler.java, pippo-core/src/main/java/ro/pippo/core/route/WebjarsResourceHandler.java
I propose you an implementation for #228. My intention was to find a simple solution with minimal modifications of the existing code.
Also I wished a solution that is independent by chosen template engine.
The current implementation uses lastModified property. For the moment all static resources are versionable.
Show me the code :)
Template: `hello.peb`
```html
<head>
<link href="{{ publicAt('css/style.css') }}" rel="stylesheet">
</head>
```
Rendered html:
```html
<head>
<link href="/public/css/style-1448911263314.css" rel="stylesheet">
</head>
```
Pippo debug console:
```
21:20:36 [qtp1963387170-13] DEBUG ro.pippo.core.util.ClasspathUtils - Located 'templates/hello.peb' in the context classpath
21:20:36 [qtp1963387170-13] DEBUG ro.pippo.core.route.DefaultRouter - Inject version in …
```
=> Versioning public resources (#228)

pippo-test/pom.xml, pippo-test/src/main/java/ro/pippo/test/PippoTest.java, pom.xml
Add the possibility for an easy testing. 
Add `PippoTest` class in a new module `pippo-test`, with a simple API, based on rest-assured [1].
I took a look on fathom-test-tools.
How to use:
1. Add the dependency to `pippo-test` in your `pom.xml`
```
<dependency>
<groupId>ro.pippo</groupId>
<artifactId>pippo-test</artifactId>
<version>${pippo.version}</version>
<scope>test</scope>
</dependency>
```
2. Add a test in your application
```java
public class RoutesTest extends PippoTest {
@Override
public Application createApplication() {
return new MyApplication();
}
@Test
public void testIndex() {
when().
get("/").
then().
statusCode(200);
}
}
```
In the current implementation, `PippoTest` creates a new `Pippo` instance for each Test. Sure, another option is to create a `Pippo` instance for all …
=> Add PippoTest

CHANGELOG.md, pippo-core/src/main/java/ro/pippo/core/ParameterValue.java, pippo-core/src/test/java/ro/pippo/core/ParameterValueTest.java
In real-world usage of Pippo I found users would "reset" a field by
overwriting a value (such as a date) with whitespace.  This would
cause exceptions when interpreting the empty values as dates.
Most ParameterValue.toSomething methods should be able to cope with
empty whitespace strings as inputs.
=> Gracefully handle parameter values composed of whitespace

pippo-controller/src/main/java/ro/pippo/controller/DefaultControllerHandler.java
We've discussed this a couple times.  Now that we are on Java 8 this is a no-brainer.
This change allows you to define a controller method like this:
```java
public class ContactsController extends Controller {
public void uriFor(int id) {
}
}
```
instead of like this:
```java
public class ContactsController extends Controller {
public void uriFor(@Param("id") int id) {
}
}
```
Of course, to have the name automatically embedded in your code **requires** modifying your project compiler flags to specify `-parameters` to javac.  Your IDE needs this specified also, separately AFAICT.
```xml
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.1</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
<compilerArguments> …
```
=> Transparently support Java 8 -parameters names for controllers

CHANGELOG.md, pippo-test/src/main/java/ro/pippo/test/PippoRule.java
This allows you to re-use the server's content type engines from your restful tests.
```java
Item item = given().accept(JSON).when().get("/api/v1/items/{id}", 1).as(Item.class);
assertEquals("Item id does not match", 1, item.getId());
assertEquals("Item name does not match", "Apples", item.getName());
```
=> Setup RestAssurred with ContentTypeEngines

pippo-core/src/main/java/ro/pippo/core/route/Route.java
when uriPattern is “/”, it will be format to an empty string,
=> a bug when route.uriPattern is "/"

pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/test/java/ro/pippo/core/DefaultRouterTest.java, pippo-core/src/test/java/ro/pippo/core/PathRegexBuilderTest.java
> I have actually gotten this to work properly now.
> I had already thought of adding a /user part to the URL but I really like the /{username} URL so I wanted to try to make that work first.
> I have also tried to exclude certain routes like /login using a PathRegexBuilder. This works but there is a bug in getting the path parameter.
> Let's say I go to the route "/Username". When I try to get the username path parameter using getPathParameter("username") it should give me the value "Username", right? Instead it gives me the value "/Username" (note that the forwardslash is included in the value). 
> I have fixed this by using the String.replace function, but this is essentially a bug I think. It only happens when I use the PathRegexBuilder.
from [google group][1]
i tried pippo `0.8.0` …
=> use Java7 Regex Named Groups fixed PathRegexBuilder wrong pathParameter bug

pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/pippo/core/route/Route.java, pippo-core/src/main/java/ro/pippo/core/route/RouteGroup.java, pippo-core/src/main/java/ro/pippo/core/util/StringUtils.java, pippo-core/src/test/java/ro/pippo/core/DefaultRouterTest.java
some description:
1, why use `setGroupUriPattern` and `absoluteUriPattern`? because i think maybe some people will repeated add route to group, like:
```
RouteGroup group1 = new RouteGroup("/users");
RouteGroup group2 = new RouteGroup("/posts");
Route route = Route.POST("like", emptyRouteHandler);
group1.addRoute(route);
group2.addRoute(route);  // it will raises an exception
```
2, why `parent-group` shared routes to `child-group`
```
public RouteGroup(RouteGroup parent, String uriPattern) {
if (parent != null) {
this.uriPattern = StringUtils.concatUriPattern(parent.getUriPattern(), uriPattern);
this.routes = parent.getRoutes();   // parent-children groups shared routes
} else {
this.uriPattern = uriPattern;
this.routes = new ArrayList<>();
}
}
```
also because maybe some people forget …
=> route group

pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/test/java/ro/pippo/core/DefaultRouterTest.java, pippo-core/src/test/java/ro/pippo/core/PathRegexBuilderTest.java
in https://github.com/decebals/pippo/pull/249 i try to use regex named group to fix wrong path parameter value bug. but there will have a new problem that underline is not supported in group name. for example if the uri pattern like `/{user_id}`, there will be a `PatternSyntaxException`:
```
java.util.regex.PatternSyntaxException: named capturing group is missing trailing '>' near index 8
/(?<user_id>[^/]+)
```
so i have to change group name from parameter name to parameter index like `/(?<param1>[^/]+)`(`/(?<1>[^/]+)` is not supported too).
=> fixed the bug when underline in path parameter name

pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java
Added the condition as @JPercivall suggested on issue #262
=> Use the trustStore only when client authentication is enabled

pippo-core/src/main/java/ro/pippo/core/Languages.java, pippo-core/src/main/java/ro/pippo/core/PippoSettings.java, pippo-core/src/main/java/ro/pippo/core/Response.java, pippo-core/src/main/java/ro/pippo/core/WebServerSettings.java, pippo-core/src/main/java/ro/pippo/core/route/Route.java, pippo-core/src/main/java/ro/pippo/core/util/ClassUtils.java, pippo-core/src/main/java/ro/pippo/core/util/ClasspathUtils.java, pippo-core/src/main/java/ro/pippo/core/util/CookieUtils.java, pippo-core/src/main/java/ro/pippo/core/util/CryptoUtils.java, pippo-core/src/main/java/ro/pippo/core/util/DateUtils.java, pippo-core/src/main/java/ro/pippo/core/util/IoUtils.java, pippo-core/src/main/java/ro/pippo/core/util/LangUtils.java, pippo-core/src/main/java/ro/pippo/core/util/PippoUtils.java, pippo-core/src/main/java/ro/pippo/core/util/StringUtils.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1118 - Utility classes should not have public constructors.
squid:S00117 - Local variable and method parameter names should comply with a naming convention.
squid:S1197 - Array designators "[]" should be on the type, not the variable.
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
squid:S00122 - Statements should be on separate lines.
squid:S2092 - Cookies should be "secure".
squid:S00115 - Constant names should comply with a naming convention.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
https://dev.eclipse.org/sonar/rules/show/squid:S00117
https://dev.eclipse.org/sonar/rules/show/squid:S1197 …
=> multiple code improvements: squid:S1118, squid:S00117, squid:S1197, squid:CommentedOutCodeLine, squid:S00122, squid:S2092, squid:S00115

pippo-fastjson/src/main/java/ro/pippo/fastjson/FastjsonInitializer.java, pippo-freemarker/src/main/java/ro/pippo/freemarker/FormatTimeMethod.java, pippo-freemarker/src/main/java/ro/pippo/freemarker/FreemarkerInitializer.java, pippo-freemarker/src/main/java/ro/pippo/freemarker/I18nMethod.java, pippo-freemarker/src/main/java/ro/pippo/freemarker/PrettyTimeMethod.java, pippo-groovy/src/main/java/ro/pippo/groovy/GroovyInitializer.java, pippo-groovy/src/main/java/ro/pippo/groovy/GroovyTemplateEngine.java, pippo-groovy/src/main/java/ro/pippo/groovy/PippoGroovyTemplate.java, pippo-gson/src/main/java/ro/pippo/gson/GsonInitializer.java, pippo-jackson/src/main/java/ro/pippo/jackson/JacksonInitializer.java, pippo-jade/src/main/java/ro/pippo/jade/JadeInitializer.java, pippo-jade/src/main/java/ro/pippo/jade/JadeTemplateEngine.java, pippo-jaxb/src/main/java/ro/pippo/jaxb/JaxbInitializer.java, pippo-pebble/src/main/java/ro/pippo/pebble/AngularJSExtension.java, pippo-pebble/src/main/java/ro/pippo/pebble/FormatTimeExtension.java, pippo-pebble/src/main/java/ro/pippo/pebble/GlobalVariablesExtension.java, pippo-pebble/src/main/java/ro/pippo/pebble/I18nExtension.java, pippo-pebble/src/main/java/ro/pippo/pebble/PebbleInitializer.java, pippo-sasscompiler/src/main/java/ro/pippo/sasscompiler/SassResourceHandler.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1068 - Unused private fields should be removed.
squid:S1854 - Dead stores should be removed.
squid:S1192 - String literals should not be duplicated.
squid:S00115 - Constant names should comply with a naming convention.
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1068
https://dev.eclipse.org/sonar/rules/show/squid:S1854
https://dev.eclipse.org/sonar/rules/show/squid:S1192
https://dev.eclipse.org/sonar/rules/show/squid:S00115
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Please let me know if you have any questions. …
=> multiple code improvements: squid:S1068, squid:S1854, squid:S1192, squid:S00115, squid:UselessParenthesesCheck

CHANGELOG.md, pippo-core/src/main/java/ro/pippo/core/Response.java, pippo-core/src/main/java/ro/pippo/core/route/DirectoryHandler.java
By flushing the response buffer we force `chunked` transfer-encoding.  When we do this we lose the option to relay `Content-Length` to the client for `HEAD` requests or for setting-up client-side deterministic download progress indicators on `GET` requests.
This PR makes `chunked` transfer encoding optional and improves the `HEAD` response of the `DirectoryHandler`.
=> Make chunked transfer-encoding optional

pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java, pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java
Hello
I investigated about `server.join();` from the `JettyServer.start()` and `tomcat.getServer().await();` from the `TomcatServer.start()`
In both cases the methods call [Thread.join()](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#join%28%29) and block the main thread of JUnit until the web server thread stops and release the main thread.
I searched how to make JUnit not work on the main thread, but I found nothing that would serve
I tried [this](http://www.codeaffine.com/2014/07/21/a-junit-rule-to-run-a-test-in-its-own-thread/) and [this](http://falutin.net/2012/12/30/multithreaded-testing-with-junit/)
We must not comment `server.join();` or `tomcat.getServer().await();` because as [AlexR](http://stackoverflow.com/questions/15924874/embedded-jetty-why-to-use-join) …
=> Workaround for Issue #273

pippo-session-cookie/src/main/java/ro/pippo/session/cookie/CookieSessionDataStorage.java, pippo-session/src/main/java/ro/pippo/session/SerializationSessionDataTranscoder.java, pippo-session/src/main/java/ro/pippo/session/SessionDataTranscoder.java
-Use [Base64](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html) JDK 8
-Use [Try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) JDK 7
-Move SessionDataTranscoder and SerializationSessionDataTranscoder to Pippo-Session to be used by other session modules that require
=> Updated Pippo Session to JDK8

pippo-session-parent/pippo-session-hazelcast/src/main/java/ro/pippo/session/hazelcast/HazelcastSessionDataStorage.java, pippo-session-parent/pippo-session-hazelcast/src/test/java/ro/pippo/session/hazelcast/HazelcastSessionDataStorageTest.java, pippo-session-parent/pippo-session-hazelcast/src/test/resources/hazelcast.xml, pippo-session-parent/pippo-session-xmemcached/src/main/java/ro/pippo/session/xmemcached/XmemcachedSessionDataStorage.java
I have made the suggested corrections
Any other recommendations is welcome
=> Isolating Hazelcast instance for each test

CHANGELOG.md, pippo-core/src/main/java/ro/pippo/core/route/DirectoryHandler.java
Normal behaviors like `connection reset by peer`, `broken pipe`, and `connection timed out` **with** their stacktrace clog the logs with useless information.  Instead log the IOException message, if available, with metadata about the request.
=> Reduce DirectoryHandler logging noise for normal IOExceptions

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/pippo/core/route/ResourceRouting.java, pippo-core/src/main/java/ro/pippo/core/route/Route.java, pippo-core/src/main/java/ro/pippo/core/route/RouteGroup.java, pippo-core/src/main/java/ro/pippo/core/route/Routing.java, pippo-core/src/main/java/ro/pippo/core/util/StringUtils.java, pippo-core/src/test/java/ro/pippo/core/DefaultRouterTest.java
I propose you an improvement of the `RouteGroup` concept. The change is small but the impact is great.
The idea is that I can create completely decoupled routes group and to create nice modular application.
A new method `addRouteGroup` was added in the `RouteGroup` class to allow us to add anytime a route group to another group. 
Before:
```java
class DemoApplication extends Application {
@Override
protected void onInit() {
addRouteGroup(new AdminRoutes(this));
}
}
class AdminRoutes extends RouteGroup {
public AdminRoutes(Application appplication) {
super("/admin");
// BEFORE FILTERS
addBeforeFilters();
// ROUTES
addRoutes();
// GROUPS
application.addRouteGroup(new UserRoutes(this));
application.addRouteGroup(new CustomerRoutes(this));
}
}
```
After:
```java
class DemoApplication extends …
```
=> Improve the route group concept

pippo-core/src/main/java/ro/pippo/core/WebServer.java, pippo-core/src/main/java/ro/pippo/core/WebServerInitializer.java, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java, pippo-server-parent/pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java, pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowServer.java
In last time I tried to improve the interoperability between `Application` and `WebServer`.
For now we can add `Filter`, `Servlet` and `Listener` in a generic/uniform mode for all builtin `WebServer` types via `WebServerInitializer` and `WebServer.addListtener(ServletContextListener listener)`.
Practically we can customize in a easy mode many aspects of the `WebServer`. Using `Pippo.setServer(WebServer server)` we can customize any aspect of the embedded server.
With the current PR I propose you a simple but powerful solution to improve the interoperability between `Application` and other services (for example __Jersey__, __Guice__ via GuiceServletContextListener and others).
With this PR you have access to the `Application` instance from `ServletConetxt`.
Below, I will show you a …
=> Inject Application instance in ServletContext

pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-core/src/main/java/ro/pippo/core/WebServer.java
A minor improvement that brings some fluency in Pippo launcher.
The old version:
```java
Pippo pippo = new Pippo();
// set port and filter path
WebServer server = pippo.getServer();
server.getSettings().port(8081);
server.setPippoFilterPath("/pippo/*");
pippo.start();
```
The new version:
```java
new Pippo()
.setFilterPath("/pippo/*")
.start(8081);
```
or
```java
new Pippo()
.setPort(8081)
.setFilterPath("/pippo/*")
.start();
```
=> Make Pippo class a little bit more expressive

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/PippoFilter.java, pippo-core/src/main/java/ro/pippo/core/PippoServlet.java, pippo-core/src/main/java/ro/pippo/core/RequestResponse.java, pippo-core/src/main/java/ro/pippo/core/RequestResponseFactory.java, pippo-core/src/main/java/ro/pippo/core/gzip/GZipFilter.java, pippo-core/src/main/java/ro/pippo/core/gzip/GZipRequestResponseFactory.java, pippo-core/src/main/java/ro/pippo/core/gzip/GZipResponseStream.java, pippo-core/src/main/java/ro/pippo/core/gzip/GZipResponseWrapper.java, pippo-session-parent/pippo-session-hazelcast/pom.xml, pippo-session-parent/pippo-session-hazelcast/src/test/java/ro/pippo/session/hazelcast/HazelcastSessionDataStorageTest.java, pippo-session-parent/pippo-session-hazelcast/src/test/resources/hazelcast.xml, pippo-session-parent/pippo-session/src/main/java/ro/pippo/session/SessionRequestResponseFactory.java
See #31 for more details.
I made some tests and everything is OK. 
So, this compression is used out of the box (you as developer do nothing) if the client (the browser - I tested on Chrome) accept "gzip" as encoding.
I made a little refactoring, `RequestResponseFactory` contains only a method `createRequestResponse(HttpServletRequest, HttpServletResponse):RequestResponse`. Practically I merged  `createRequest` and `createResponse` methods in one method `createRequestResponse` because are multiple situation when I need to have access from response to request and vice versa. I hope that this modification doesn't affect you.
Of course any advice, question is welcome.
=> Use gzip compression where it's possible; see #331

pippo-core/src/main/java/ro/pippo/core/ParameterValue.java, pippo-core/src/test/java/ro/pippo/core/ParameterValueTest.java
Return empty list when `toList()` is called for parameter with empty string as its value
=> Fixes #338

pippo-core/src/main/java/ro/pippo/core/Response.java, pippo-core/src/test/java/ro/pippo/core/ResponseTest.java
@decebals,
This is required because on calling `httpServletResponse.reset()`, only response gets reset. But other params like headers, cookies also need to erased from `Response` class
=> feat(Response): expose method to reset the response

pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/Controller.java, pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/ControllerApplication.java, pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/ControllerRegistry.java, pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/ControllerRouteHandler.java
This PR offers you the possibility to specify a Controller instance for all requests (singleton).
```java
addControllers(ContactsController.class); // one instance for EACH request
// or
addControllers(new ContactsController()); // one instance for ALL requests
```
See #324 for details.
=> Add possibility to use a singleton Controller

pippo-core/src/main/java/ro/pippo/core/AbstractWebServer.java, pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-core/src/main/java/ro/pippo/core/WebServer.java, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java, pippo-server-parent/pippo-tjws/src/main/java/ro/pippo/tjws/TjwsServer.java, pippo-server-parent/pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java, pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowServer.java
This modification help me to move forward the branch with the WebSocket support (that will be available in next release).
I believe that this move is natural and it adds more clarity to API. It's the responsibility of `WebServer` to deals with `PippoFilter`.
The drawback is that this PR comes with a change in the API but, the change is in a zone that it's too visited.
=> Move PippoFilter instantiation from Pippo class to the WebServer implementations (breaking change)

pippo-core/src/main/java/ro/pippo/core/AbstractWebServer.java, pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-core/src/main/java/ro/pippo/core/PippoFilter.java, pippo-core/src/main/java/ro/pippo/core/Request.java, pippo-core/src/main/java/ro/pippo/core/WebServer.java, pippo-core/src/main/java/ro/pippo/core/websocket/AbstractWebSocketFilter.java, pippo-core/src/main/java/ro/pippo/core/websocket/WebSocketConnection.java, pippo-core/src/main/java/ro/pippo/core/websocket/WebSocketContext.java, pippo-core/src/main/java/ro/pippo/core/websocket/WebSocketHandler.java, pippo-core/src/main/java/ro/pippo/core/websocket/WebSocketProcessor.java, pippo-server-parent/pippo-jetty/pom.xml, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/websocket/JettyWebSocketConnection.java, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/websocket/JettyWebSocketFilter.java, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/websocket/JettyWebSocketProcessor.java, pippo-server-parent/pippo-tjws/src/main/java/ro/pippo/tjws/TjwsServer.java, pippo-server-parent/pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java, pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowServer.java
It's the successor of #279. All information presented in #279 are available.
=> Websocket support

pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java
This might need some further work, but I thought I'd share to get the discussion started. I wanted to put a dummy self-signed cert in my JAR to use when in dev mode, and I discovered that I couldn't figure out a way to set `server.keystoreFile` in `application.properties` that would load it. If running from a JAR, Jetty wants a jar:file:/... style path. But if just running in my IDE, I need a file-system relative path. With this change I can add `%dev.server.keystoreFile = /pippo_self_signed.pkcs12` to my application.properties and it works in both cases without further modification. (`pippo_self_signed.pkcs12` resides in my `src/main/resources` folder)
=> Handle keystore paths that are relative to Classpath

pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowServer.java, pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowSettings.java
- Pick undertow options from pippoSettings.
- All parameters would be in this format undertow.<type>.<parameter>
type has 3 values - server, socket, worker
Currently maintaining map in `UndetowSettings` which maintains mapping between parameter and its type.
If this approach is okay, I will add more parameters to map in `UndertowSettings` to the parameter list as extensive. 
Also, Could you suggest way to add any parameter without using map (currently map has to be maintained to know parameter type)
This fix is related to issue #359
=> Add support to configure undertow

pippo-core/src/main/java/ro/pippo/core/AbstractTemplateEngine.java, pippo-core/src/main/java/ro/pippo/core/PippoConstants.java, pippo-core/src/test/java/ro/pippo/core/AbstractTemplateEngineTests.java, pippo-template-parent/pippo-freemarker/src/main/java/ro/pippo/freemarker/FreemarkerTemplateEngine.java, pippo-template-parent/pippo-groovy/src/main/java/ro/pippo/groovy/GroovyTemplateEngine.java, pippo-template-parent/pippo-jade/src/main/java/ro/pippo/jade/JadeTemplateEngine.java, pippo-template-parent/pippo-pebble/src/main/java/ro/pippo/pebble/PebbleTemplateEngine.java, pippo-template-parent/pippo-trimou/src/main/java/ro/pippo/trimou/TrimouTemplateEngine.java
This change allows customizing the file extension used by `PebbleTemplateEngine` from the default of `.peb`. The customization can be applied by adding the following line in `conf/application.properties`:
```properties
template.extension = pebble
```
The same can be used by other pippo template integrations.
=> TemplateEngine customization and extension support 

pippo-core/src/main/java/ro/pippo/core/ParameterValue.java, pippo-core/src/test/java/ro/pippo/core/ParameterValueTest.java
@decebals 
> Not related to this commit. Sharing it here instead of raising separate issue
```
https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/ParameterValue.java#L247
If values has single entry, 
toSet() handles it differently compared to toList(). Is there any reason for this behavior??
In toSet() method, value is split only on ,(comma) unlike toList(). I think, the behavior should be similar to toList(). 
```
=> Remove code duplication from ParameterValue

LICENSE, pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/ControllerRegistry.java, pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java, pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/DefaultErrorHandler.java, pippo-core/src/main/java/ro/pippo/core/DefaultUriMatcher.java, pippo-core/src/main/java/ro/pippo/core/ParameterValue.java, pippo-core/src/main/java/ro/pippo/core/UriMatcher.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/pippo/core/route/Routing.java, pippo-core/src/main/java/ro/pippo/core/websocket/AbstractWebSocketFilter.java, pippo-core/src/main/java/ro/pippo/core/websocket/WebSocketContext.java, pippo-core/src/main/java/ro/pippo/core/websocket/WebSocketRouter.java, pippo-core/src/main/resources/pippo/pippo-messages_pl.properties, pippo-core/src/test/java/ro/pippo/core/DefaultErrorHandlerTest.java, pippo-core/src/test/java/ro/pippo/core/ParameterValueTest.java, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/websocket/JettyWebSocketAdapter.java, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/websocket/JettyWebSocketFilter.java, pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/websocket/UndertowWebSocketAdapter.java, pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/websocket/UndertowWebSocketFilter.java
This PR contains a functional POC (prof of concept) for #395.
The code works but need some adjustment.
For Undertow:
```java
addWebSocket("/ws/chat/{room}", (webSocketContext, message) -> {
WebSocketConnection connection = webSocketContext.getConnection();
// cast WebSocketConnection to UndertowWebSocketConnection
UndertowWebSocketConnection undertowConnection = (UndertowWebSocketConnection) connection;
String remoteAddress = undertowConnection.getRemoteAddress().toString();
System.out.println("remoteAddress = " + remoteAddress);
WebSocketHttpExchange exchange = undertowConnection.getExchange();
String query = exchange.getQueryString();
System.out.println("query = " + query);
});
```
For Jetty the code is similar with the code presented in …
=> Add path params in websocket uri

pippo-core/src/main/java/ro/pippo/core/PippoSettings.java, pippo-core/src/test/java/ro/pippo/core/PippoSettingsTest.java
This would help the user to specify properties like below,
`key=[value1, value2, value3]` (more verbose)
Based on 
https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/ParameterValue.java#L277
=> Remove braces from start and end in getStrings

pippo-core/src/main/java/ro/pippo/core/ParameterValue.java
This is to be consistent with toList() which returns immutable List
Extension of PR #403
=> Return immutable Set when toSet() is called

pippo-core/src/main/java/ro/pippo/core/ParameterValue.java, pippo-core/src/test/java/ro/pippo/core/ParameterValueTest.java
`ParameterValue`  when converting numbers does not consider locale. For example: in Brazil the decimal part (fraction) is separated with a `,` (comma), not with a `.` (dot) as in US. Therefore, is not possible submit, for example: `1234,45` or `1.234,56`
In this Pull Request I solved this problem. The `Locale` default is `Locale.getDefault()` and you have the option to pass a specific Locale.
I have adapted the tests and added more tests.
Please, tell me if it is all fine and if any change is necessary.
=> Convert to float, double and BigDecimal according Locale

pippo-metrics-parent/pippo-metrics-prometheus/README.md, pippo-metrics-parent/pippo-metrics-prometheus/pom.xml, pippo-metrics-parent/pippo-metrics-prometheus/src/main/java/ro/pippo/prometheus/Reporter.java, pippo-metrics-parent/pom.xml
This PR comes to solve #415.
Add the following dependency to your application pom.xml:
```xml
<dependency>
<groupId>ro.pippo</groupId>
<artifactId>pippo-metrics-prometheus</artifactId>
<version>${pippo.version}</version>
</dependency>
```
Add the following settings to your application.properties:
```properties
metrics.prometheus.enabled = true
metrics.prometheus.address = prometheus.example.com // default 'localhost'
metrics.prometheus.port = 9091
metrics.prometheus.period = 60 seconds
```
=> Add support for Prometheus (metrics)

pippo-core/src/main/java/ro/pippo/core/FileItem.java
write method of file item doesn't closed newly created `inputStream` post usage
this fix closes it in a finally block
=> FileItem's inputstream is closed properly now

pippo-metrics-parent/pippo-metrics/src/main/java/ro/pippo/metrics/CountedHandler.java, pippo-metrics-parent/pippo-metrics/src/main/java/ro/pippo/metrics/MeteredHandler.java, pippo-metrics-parent/pippo-metrics/src/main/java/ro/pippo/metrics/MetricsInitializer.java, pippo-metrics-parent/pippo-metrics/src/main/java/ro/pippo/metrics/MetricsTransformer.java, pippo-metrics-parent/pippo-metrics/src/main/java/ro/pippo/metrics/TimedHandler.java
Before this PR we register a meter metric for a route (handler) with `@Metered` annotation
```java
// send a template as response
GET("/template", new RouteHandler() {
@Metered
public void handle(RouteContext routeContext) {
routeContext.render("hello"); // render "hello" template
}
});
```
The inconvenient here is that I am forced to create an anonymous class and that the meter name is compose from the class name (useless in this case) and the method name ("handle"). So, the meter name is useless.
This approach with `@Metered` annotation on `handle` method is useful when we have concrete route handler
```java
public class MyHandler implements RouteHandler {
@Metered
public void handle(RouteContext routeContext) {
routeContext.render("hello"); // render "hello" template
}
}
```
In this …
=> Call SharedMetricRegistries.setDefault in MetricsInitializer

pippo-core/src/main/java/ro/pippo/core/PippoSettings.java
I've encountered a problem where the strings read from PippoSettings were garbling German Umlauts. This is because the File is not opened as a UTF-8 file, but instead with the local encoding. This PR now opens the Settings File always as UTF-8.
As an alternative I've tested supplying -Dfile.encoding=UTF8 to the JVM instead the pathc, but it is not helping.
=> The Settings File is now read with UTF-8 as the default encoding.

pippo-core/src/main/java/ro/pippo/core/gzip/GZipFilter.java, pippo-core/src/main/java/ro/pippo/core/gzip/GZipRequestResponseFactory.java, pippo-core/src/test/java/ro/pippo/core/gzip/GZipRequestResponseFactoryTest.java
* When explicit * is specified in Accept-Encoding then send
gzip response
Fixes #473
@decebals This PR doesn't include `qvalue` changes
=> feat(gzip): send gzip response when Accept-Encoding:* is present

pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/websocket/UndertowWebSocketConnection.java
=> Issue #480 - Use WebSockets.sendClose to send close code/reason

pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/websocket/UndertowWebSocketAdapter.java
Fix for #495 - move channel resume to the end of the `onConnect` method
=> Issue #495 - do not call channel.resumeReceives() until handler.onOpen() called

pippo-content-type-parent/pippo-fastjson/pom.xml
* http://repo1.maven.org/maven2/com/alibaba/fastjson/1.2.57/
* This fixes fastjson test failures in different timezones
* This also has some performance improvements
=> chore: upgrade fastjson to latest version

pippo-content-type-parent/pippo-gson/src/main/java/ro/pippo/gson/GsonEngine.java, pippo-content-type-parent/pippo-jaxb/src/main/java/ro/pippo/jaxb/JaxbEngine.java, pippo-content-type-parent/pippo-snakeyaml/src/main/java/ro/pippo/snakeyaml/SnakeYamlEngine.java, pippo-content-type-parent/pippo-xstream/src/main/java/ro/pippo/xstream/XstreamEngine.java
Solves #534 
Reuse de/serialization engines
To check
=> ContentTypeEngine improvement

pippo-controller-parent/pippo-controller/src/test/java/ro/pippo/controller/util/ClassUtilsTest.java
* ClassUtilsTest fails in java11. This fixes the issue
Fix based on [this](https://stackoverflow.com/questions/50456726/mockclassloader-cannot-access-jdk-internal-reflect-superclass-jdk-internal-refle)
=> fix failing test in java11

pippo-core/src/main/java/ro/pippo/core/gzip/GZipResponseWrapper.java
Calling close twice on the stream will throw an exception ( which is silently ignored ). 
I don't think this change has any effect. It is just annoying if you debug your application and set the debugger to halt on every exception and see it halting within Pippo.
=> Closing the writer will close the stream as well. Fix for #455.

pippo-core/src/main/java/ro/pippo/core/gzip/GZipResponseStream.java
=> Close gzipOutputStream after the usage

pippo-template-parent/pippo-pebble/src/main/java/ro/pippo/pebble/PebbleTemplateEngine.java
I cannot use the excellent [Pebble IntelliJ plugin](https://github.com/bjansen/pebble-intellij) to navigate on `include/extends`:
```
{% extends "base" %}
```
If I disabled the suffix (`.peb` that is added to the template name) I can navigate with CTRL + MOUSE CLICK to referenced template
```
{% extends "base.peb" %}
```
The easy mode is to add a new `pebble.suffix.enabled` in `application.properties` as:
```
pebble.suffix.enabled = false
```
Of course is you disable the suffix (`.peb`) you render the template with:
```java
Map<String, Object> model = new HashMap<>();
model.put("users", ticketingService.getUsers());
routeContext.render("users.peb", model);
```
instead 
```java
Map<String, Object> model = new HashMap<>();
model.put("users", ticketingService.getUsers()); …
```
=> Add possibility to disable suffix for Pebble loader

pippo-core/src/test/java/ro/pippo/core/route/PathTraversalResourceHandlerTest.java
This is a test refactoring.
**Problem:**
Conditions within the test method will alter the behavior of the test and its expected output, and would lead to situations where the test fails to detect defects in the production method since test statements were not executed as a condition was not met.
**Solution:**
Instead of using a conditional to control the test execution, we use the proper JUnit API with assertNotNull().
**Result:**
_Before:_
if (url != null) {
assertTrue("Path traversal security issue", Paths.get(url.toURI()).startsWith(basePath));
}
_After:_
Assert.assertNotNull(url);
assertTrue("Path traversal security issue", Paths.get(url.toURI()).startsWith(basePath));
=> Test improvement

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java
With this very simple modification I can extract the part with routes from `Application` in custom `Router`.
See below an example using Spring IoC:
```java
@Component
public class MyRouter extends DefaultRouter {
@Autowired
private List<RouteGroup> routeGroups;
@Autowired
private List<Route> routes;
@PostConstruct
public void addRoutes() {
// ignore icon
ignorePaths("/favicon.ico");
// add routes for static content
addPublicResourceRoute();
addWebjarsResourceRoute();
// filter that inject some info
ANY("/.*", routeContext -> {
routeContext.setLocal("version", version);
routeContext.next();
});
// add registered routes
routeGroups.forEach(this::addRouteGroup);
routes.forEach(this::addRoute);
GET("/threadDump", new ThreadDumpHandler());
GET("/sysInfo", new SystemInfoHandler());
}
}
```
=> Add resource route helper in router

pom.xml
1.7 is not compatible with Java 11 and causes warnings in tests:
[WARNING] Supported source version 'RELEASE_8' from annotation processor 'org.kohsuke.metainf_services.AnnotationProcessorImpl' less than -source '11'
=> Bump version of metainf-services to 1.9

pippo-test/src/main/java/ro/pippo/test/AvailablePortFinder.java
As requested in https://github.com/pippo-java/pippo/issues/632#issuecomment-1431320266
=> Better detection of free port to bind to
