README.md, pippo-core/src/main/java/ro/fortsoft/pippo/core/HttpConstants.java, pippo-demo/pom.xml, pippo-snakeyaml/pom.xml, pippo-snakeyaml/src/main/java/ro/fortsoft/pippo/snakeyaml/SnakeYamlEngine.java, pippo-snakeyaml/src/main/java/ro/fortsoft/pippo/snakeyaml/SnakeYamlInitializer.java, pippo-snakeyaml/src/main/resources/pippo.properties, pippo-snakeyaml/src/main/resources/services/ro.fortsoft.pippo.core.ContentTypeEngine, pom.xml
YAML is a common interchange format for services.
=> Add content-type engine for YAML

pippo-core/src/main/java/ro/fortsoft/pippo/core/PippoFilter.java
All responses start out as 200 OK from the underlying container because they have
been matched by PippoFilter.  A Pippo application must then handle that response and
either preserve the 200 or set it differently.
If the handler chain does not explicitly commit the response, PippoFilter should treat
this as a successful operation, like the underlying servlet framework would.
In the event that the uncommitted response has an error status (>= 400) then the
error handler should be called to return the appropriate representation of that error:
xml, json, html, etc.
The auto-commit behavior should be logged and the final status code of all responses
should be logged too.
This proposal is related to #66.
=> Allow PippoFilter to auto-commit uncommitted responses

pippo-core/src/main/java/ro/fortsoft/pippo/core/Response.java
This PR documents & moves methods to group similar functionality.
- things that set headers
- things that handle cookies
- things that commit the response
- etc
I also added `yaml()` and `yaml(object)` methods to make working with that content type convenient.
This is related to #66.
=> Reorganize and document the Response class

pippo-core/src/main/java/ro/fortsoft/pippo/core/Application.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/HttpConstants.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/route/ClasspathResourceHandler.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/fortsoft/pippo/core/route/Router.java, pippo-core/src/test/java/ro/fortsoft/pippo/core/DefaultRouterTest.java, pippo-demo/pippo-demo-crud/src/main/java/ro/fortsoft/pippo/demo/crud/CrudApplication.java, pippo-demo/pippo-demo-crudng/src/main/java/ro/fortsoft/pippo/demo/crudng/CrudNgApplication.java
RFC - I tried a very simple implementation without many changes in sources.
=> add support for ALL (request method) - useful for filters

README.md, pippo-core/src/main/java/ro/pippo/core/PippoConstants.java, pippo-core/src/main/java/ro/pippo/core/WebServerSettings.java, pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java
=> Remove the legacy external files feature

pippo-core/src/main/java/ro/pippo/core/PippoSettings.java
Initial use-case would be...
Bundle `conf/application.properties` in your app which defines an override setting:
```properties
override = ${user.dir}/my.properties
```
The classpath settings are the base, the external settings overwrite classpath settings.
This could be further extended to support key references within other values, but I stopped-short of that.
```properties
my.url = http://somewhere.com:${server.port}/${server.contextPath}
```
=> Implement an 'override' mechanism and System property & Env variable interpolation

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/DefaultSession.java, pippo-core/src/main/java/ro/pippo/core/DefaultSessionFactory.java, pippo-core/src/main/java/ro/pippo/core/Request.java, pippo-core/src/main/java/ro/pippo/core/ResponseFactory.java, pippo-core/src/main/java/ro/pippo/core/Session.java, pippo-core/src/main/java/ro/pippo/core/SessionFactory.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouteHandlerChainFactory.java, pippo-demo/pippo-demo-crud/src/main/java/ro/pippo/demo/crud/CrudApplication.java, pippo-demo/pippo-demo-crudng/src/main/java/ro/pippo/demo/crudng/CrudNgApplication.java
`Session` is a an interface with a `DefaultSession` implementation based on `HttpSession`. You can create an use in your application a custom session (for example a signed cookie session).
=> Allow to use a custom session

pippo-core/src/main/java/ro/pippo/core/PippoFilter.java
Do you see any reason why we shouldn't automatically decode paths?
=> Use URI to automatically decode %nn encoded url paths

pippo-core/src/main/java/ro/pippo/core/PippoFilter.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouter.java, pippo-core/src/main/java/ro/pippo/core/route/Router.java, pippo-demo/pippo-demo-basic/src/main/java/ro/pippo/demo/basic/BasicApplication.java, pippo-demo/pippo-demo-basic/src/main/java/ro/pippo/demo/basic/BasicDemo.java
I think it is cleaner to specify ignore paths using the `Router` than to configure `PippoFilter` separately.
Thoughts?
=> Move ignore paths feature into Router

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/PippoFilter.java, pippo-demo/pippo-demo-basic/src/main/java/ro/pippo/demo/basic/BasicApplication.java, pippo-demo/pippo-demo-controller/src/main/java/ro/pippo/demo/controller/ControllerApplication.java, pippo-demo/pippo-demo-crud/src/main/java/ro/pippo/demo/crud/CrudApplication.java, pippo-demo/pippo-demo-crudng/src/main/java/ro/pippo/demo/crudng/CrudNgApplication.java, pippo-demo/pippo-demo-custom/src/main/java/ro/pippo/demo/custom/CustomApplication.java, pippo-demo/pippo-demo-guice/src/main/java/ro/pippo/demo/guice/GuiceApplication.java, pippo-demo/pippo-demo-guice/src/main/java/ro/pippo/demo/guice/GuiceApplication2.java, pippo-demo/pippo-demo-spring/src/main/java/ro/pippo/demo/spring/SpringApplication.java, pippo-demo/pippo-demo-spring/src/main/java/ro/pippo/demo/spring/SpringApplication2.java, pippo-demo/pippo-demo-template/src/main/java/ro/pippo/demo/template/TemplateApplication.java, pippo-demo/pippo-demo-upload/src/main/java/ro/pippo/demo/upload/UploadApplication.java, pippo-demo/pippo-demo-validation/src/main/java/ro/pippo/demo/validation/ValidationApplication.java
Method names may need tweaking.
=> Move Initializers from PippoFilter to Application

pippo-core/src/main/java/ro/pippo/core/DefaultErrorHandler.java
Because our error handler is so cool and calls itself we can end up in a recursive death spiral.
This PR implements a trap which prevents infinite recursion.  I believe the depth limit is correct - it's based on throwing an exception during rendering of a template while we are handling a different exception/status code.
If we discover the depth is incorrect, that's easy enough to tweak.
=> Trap recursion in error handler

README.md, pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java, pippo-undertow/pom.xml, pippo-undertow/src/main/java/ro/pippo/undertow/UndertowServer.java, pippo-undertow/src/main/resources/META-INF/services/ro.pippo.core.WebServer, pom.xml
I've been sitting on this for a while.  Time to upstream it.
=> Add Undertow WebServer implementation

README.md, pippo-core/src/main/java/ro/pippo/core/Response.java, pippo-tjws/pom.xml, pippo-tjws/src/main/java/ro/pippo/tjws/TjwsServer.java, pippo-tjws/src/main/resources/META-INF/services/ro.pippo.core.WebServer, pom.xml
Maybe worthwhile, maybe not.  I also checked out [Winstone](https://code.google.com/p/winstone) but it doesn't appear to have an API but it is an interesting micro-container.
=> RFC: Add a Tjws WebServer implementation

pippo-demo/pippo-demo-ajax/pom.xml, pippo-demo/pippo-demo-ajax/src/main/java/ro/pippo/demo/ajax/AjaxApplication.java, pippo-demo/pippo-demo-ajax/src/main/java/ro/pippo/demo/ajax/AjaxDemo.java, pippo-demo/pippo-demo-ajax/src/main/resources/conf/application.properties, pippo-demo/pippo-demo-ajax/src/main/resources/simplelogger.properties, pippo-demo/pippo-demo-ajax/src/main/resources/templates/index.ftl, pippo-demo/pippo-demo-ajax/src/main/webapp/WEB-INF/web.xml, pippo-demo/pom.xml
=> add pippo-demo-ajax based on intercooler.js

pippo-tomcat/pom.xml, pippo-tomcat/src/main/java/ro/pippo/tomcat/EmptyServlet.java, pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java, pippo-tomcat/src/main/resources/META-INF/services/ro.pippo.core.WebServer, pom.xml
=> Filter implementation

pippo-tomcat/pom.xml, pippo-tomcat/src/main/java/ro/pippo/tomcat/EmptyServlet.java, pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java, pippo-tomcat/src/main/resources/META-INF/services/ro.pippo.core.WebServer, pom.xml
=> Revert "Revert "add Tomcat support""

pippo-undertow/src/main/java/ro/pippo/undertow/UndertowServer.java, pippo-undertow/src/main/java/ro/pippo/undertow/UndertowSettings.java
Add more configuration options for Undertow server.
Example of application.properties:
...
#undertow
undertow.bufferSize = 32768
undertow.buffersPerRegion = 20
undertow.directBuffers = true
undertow.ioThreads = 4
undertow.workerThreads = 64
...
=> Added more configuration options for undertow

pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java, pippo-jetty/src/main/java/ro/pippo/jetty/JettySettings.java
Implements QueuedThreadPool.
In application.properties you can set:
jetty.maxThreads = 100
jetty.minThreads = 10
jetty.threadTimeout =30000
(threadTimeout in milliseconds)
=> Add more configurations to Jetty server

pippo-core/src/main/java/ro/pippo/core/RedirectHandler.java, pippo-core/src/main/java/ro/pippo/core/Response.java, pippo-core/src/main/java/ro/pippo/core/route/DefaultRouteContext.java, pippo-core/src/main/java/ro/pippo/core/route/RouteContext.java
- add `RouteContext.redirect(String nameOrUriPattern, Map<String, Object> parameters)`
- add constructor `RedirectHandler(String nameOrUriPattern, Map<String, Object> parameters)`
=> add support for redirect to route

pippo-less4j/src/main/java/ro/pippo/less4j/LessResourceHandler.java
Rework by putting the less compiler as local variable for non thread safe access.
Add a fluent method for configuring minimized mode.
=> Css preprocessor

pippo-less4j/src/main/java/ro/pippo/less4j/LessResourceHandler.java, pippo-sasscompiler/src/main/java/ro/pippo/sasscompiler/SassResourceHandler.java
Changed the way the cache for generated css works
=> add entries to cache map only on PROD mode

pippo-demo/pippo-demo-weld/pom.xml, pippo-demo/pippo-demo-weld/src/main/resources/conf/application.properties, pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java, pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatSettings.java
Added the https connector for Tomcat and a settings class for custom Tomcat settings
=> Tomcat ssl

pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java
Added trustStoreFile and trustStorePass properties for ssl configuration
=> ssl for tomcat

pippo-weld/pom.xml
Upgrade Weld to 2.2.14.Final version
=> Upgrade Weld version

pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-demo/pippo-demo-basic/src/main/java/ro/pippo/demo/basic/HelloWorld.java
I see a lot of guys who want to compare (web) frameworks in terms of the number of characters used for a Hello World application. This PR is for these guys. 
```java
Pippo.send("Hello World");
```
Now Pippo is the best :)
=> add super simple hello world

pippo-tomcat/pom.xml
=> Upgrade Tomcat version

pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java
=> Allow multipart upload

pippo-core/src/main/java/ro/pippo/core/Request.java
A pull-request to implement a try-catch for the issue reported in #209
=> try-catch, defaults to string param

pippo-tomcat/pom.xml
=> Upgrade Tomcat to 8.0.28

pippo-weld/pom.xml
Upgrade weld version to 2.3.1.Final
=> Upgrade weld version to 2.3.1.Final

pippo-less4j/pom.xml
=> Upgrade less4j to 1.15.2

CHANGELOG.md
=> Added changelog update

pippo-less4j/src/main/java/ro/pippo/less4j/LessResourceHandler.java, pippo-sasscompiler/pom.xml, pippo-sasscompiler/src/main/java/ro/pippo/sasscompiler/SassResourceHandler.java
add the minify option for sass compiler
=> Upgrade sasscompiler

CHANGELOG.md, pippo-csv/pom.xml, pippo-csv/src/main/java/ro/pippo/csv/Csv.java, pippo-csv/src/main/java/ro/pippo/csv/CsvEngine.java, pippo-csv/src/main/java/ro/pippo/csv/CsvInitializer.java, pippo-csv/src/main/resources/META-INF/services/ro.pippo.core.ContentTypeEngine, pippo-csv/src/main/resources/META-INF/services/ro.pippo.core.Initializer, pippo-csv/src/test/java/ro/pippo/csv/CsvEngineTest.java, pom.xml
This engine allows you to send an array of objects as CSV content.
It also allows you to deserialize CSV into objects.
=> Add pippo-csv content-type engine

CHANGELOG.md, pippo-pebble/pom.xml, pippo-pebble/src/main/java/ro/pippo/pebble/FormatTimeExtension.java, pippo-pebble/src/main/java/ro/pippo/pebble/GlobalVariablesExtension.java, pippo-pebble/src/main/java/ro/pippo/pebble/I18nExtension.java, pippo-pebble/src/main/java/ro/pippo/pebble/PebbleTemplateEngine.java, pippo-pebble/src/main/java/ro/pippo/pebble/PrettyTimeExtension.java
Satisfies #232 .
There are some behavior differences to note in Pebble 2.  I'm still checking that in my apps but I think this update is solid.
=> Update to Pebble 2.2.1

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-core/src/main/java/ro/pippo/core/route/Routing.java
The idea is that I can add routes directly in `Pippo` class without use `getApplication()` method.
I don't know if `Routing` is a good/clear name. Or maybe `RouteAware` is better. My English is not so good so I cannot help in this direction.
What you say? Is it a valuable PR?
=> Extract addRoute, GET, POST, ... methods in Routing interface

pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/SingletonControllerFactory.java
If you want singleton instances for controllers:
```java
public class MyApplication extends ControllerApplication {
@Override
protected void onInit() {
// set singleton controller factory
setControllerFactory(new SingletonControllerFactory());
...
}
}
```
`SingletonControllerFactory` comes with optional goodies, please read the javadoc for more information.
=> Add SingletonControllerFactory, a possible solution for #324

pippo-core/src/main/java/ro/pippo/core/route/Route.java
setAbsoluteUriPattern should be public to allow custom implementation of Router
=> Make Route::setAbsoluteUriPattern public 

pippo-core/src/main/java/ro/pippo/core/Response.java
@decebals Please review
Fixes #335
=> add getWriter method to Response

pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-core/src/main/java/ro/pippo/core/PippoConstants.java, pippo-core/src/main/java/ro/pippo/core/reload/ReloadClassLoader.java, pippo-core/src/main/java/ro/pippo/core/reload/ReloadWatcher.java, pippo-core/src/main/java/ro/pippo/core/route/ClasspathResourceHandler.java, pippo-core/src/main/java/ro/pippo/core/route/WebjarsResourceHandler.java, pippo-core/src/main/java/ro/pippo/core/util/IoUtils.java, pippo-core/src/main/java/ro/pippo/core/util/ServiceLocator.java, pippo-core/src/test/java/ro/pippo/core/route/PathTraversalResourceHandlerTest.java
This feature allows you to write code (services, web routes, ...), save the code on disk and reload the web page from browser without restart the application (from IDE).
```java
import org.kohsuke.MetaInfServices;
@MetaInfServices
public class PippoApplication extends Application {
@Override
protected void onInit() {
GET("/", routeContext -> routeContext.send("Hello"));
}
}
```
```java
public class PippoLauncher {
public static void main(String[] args) {
Pippo pippo = new Pippo();
pippo.start();
}
}
```
So, the code is almost the same. The only one difference is that you must specify your application class name and NOT to create the application instance.
You can supply the application class name:
- create by hand a `META-INF/services/ro.pippo.core.Application` file with content …
=> Hot reloading implementation

pippo-core/src/main/java/ro/pippo/core/route/TrailingSlashHandler.java
How to use:
```java
public class MyApplication extends Application {
@Override
protected void onInit() {
// add trailing slash filter
ALL("/.*", new TrailingSlashHandler(false)); // remove trailing slash
// test for #366
GET("/test", routeContext -> routeContext.send("Test !!!"));
}
}
```
Now, if you type `localhost/test` or `localhost/test/` in browser, the result is the same.
For more information/details about the internal process, please read the javadoc of `TrailingSlashHandler` class.
=> Resolve #366

pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java, pippo-server-parent/pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java
JettyRule with JettyServer hangs when multiple tests present.
=> A possible solution for #371

pippo-core/src/main/java/ro/pippo/core/Pippo.java, pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java
This is the simplified Jetty Startup I proposed to address #375
=> Jetty startup

pippo-core/src/main/java/ro/pippo/core/DefaultErrorHandler.java, pippo-core/src/test/java/ro/pippo/core/DefaultErrorHandlerTest.java
Fixing issue #396 unexpected ErrorHandling behavior
=> 396-errorHandler-not-working-properly

pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/ControllerRegistry.java, pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java
Resolve #400 Duplicate routes being created
=> Resolve #400

pippo-template-parent/pippo-freemarker/pom.xml, pippo-template-parent/pippo-freemarker/src/main/resources/templates/pippo/000base.ftl
Satisfies #421
Any doubt I am available!
=> Update pippo-freemarker to Freemarker 2.3.28

README.md
The dependencies for the jetty server is missing hence added the same.
=> Updated the right dependencies

pippo-core/src/main/java/ro/pippo/core/route/PingHandler.java, pippo-core/src/main/java/ro/pippo/core/route/SettingsHandler.java, pippo-core/src/main/java/ro/pippo/core/route/SystemInfoHandler.java, pippo-metrics-parent/pippo-metrics/pom.xml, pippo-metrics-parent/pippo-metrics/src/main/java/ro/pippo/metrics/HealthCheckHandler.java, pippo-metrics-parent/pippo-metrics/src/main/java/ro/pippo/metrics/MetricsHandler.java, pippo-metrics-parent/pippo-metrics/src/main/java/ro/pippo/metrics/ThreadDumpHandler.java
I added small route handlers that are useful in my opinion for an admin.
```java
GET("/ping", new PingHandler());
GET("/threadDump", new ThreadDumpHandler());
GET("/metrics", new MetricsHandler());
GET("/healthCheck", new HealthCheckHandler(healthCheckRegistry));
GET("/settings", new SettingsHandler());
GET("/sysInfo", new SystemInfoHandler());
```
=> Add useful handlers for admin

pippo-core/src/main/java/ro/pippo/core/util/IoUtils.java
=> Make methods statics in IoUtils

pippo-content-type-parent/pippo-jackson/pom.xml
=> feat: upgrade jackson to latest version

pippo-controller-parent/pippo-guice/pom.xml
* With this version, the multi-binding extension would be part of
main Guice package
@decebals Please review
=> feat: upgrade guice to latest version

pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowSettings.java
Fixes #462 
This has been tested with an independent project.
=> fix(undertow): resolve undertow settings not getting picked

pippo-session-parent/pippo-session-cookie/src/main/java/ro/pippo/session/cookie/CookieSessionDataStorage.java, pippo-session-parent/pippo-session-ehcache2/src/main/java/ro/pippo/session/ehcache/EhcacheSessionDataStorage.java, pippo-session-parent/pippo-session-ehcache3/src/main/java/ro/pippo/session/ehcache/EhcacheSessionDataStorage.java, pippo-session-parent/pippo-session-hazelcast/src/main/java/ro/pippo/session/hazelcast/HazelcastSessionDataStorage.java, pippo-session-parent/pippo-session-infinispan/src/main/java/ro/pippo/session/infinispan/InfinispanSessionDataStorage.java, pippo-session-parent/pippo-session-jcache/src/main/java/ro/pippo/session/jcache/JCacheSessionDataStorage.java, pippo-session-parent/pippo-session-jdbc/src/main/java/ro/pippo/session/jdbc/JDBCSessionDataStorage.java, pippo-session-parent/pippo-session-jedis/src/main/java/ro/pippo/session/jedis/JedisSessionDataStorage.java, pippo-session-parent/pippo-session-mongodb/src/main/java/ro/pippo/session/mongodb/MongoDBSessionDataStorage.java, pippo-session-parent/pippo-session-spymemcached/src/main/java/ro/pippo/session/spymemcached/SpymemcachedSessionDataStorage.java, pippo-session-parent/pippo-session-xmemcached/src/main/java/ro/pippo/session/xmemcached/XmemcachedSessionDataStorage.java, pippo-session-parent/pippo-session/src/main/java/ro/pippo/session/DefaultSessionData.java, pippo-session-parent/pippo-session/src/main/java/ro/pippo/session/MemorySessionDataStorage.java, pippo-session-parent/pippo-session/src/main/java/ro/pippo/session/SessionData.java, pippo-session-parent/pippo-session/src/test/java/ro/pippo/session/EncryptedSessionDataTranscoderTest.java
DefaultSessionData is the implementation previously in SessionData
=> Made SessionData an interface, and introduced DefaultSessionData

pippo-content-type-parent/pippo-fastjson/pom.xml
=> Updated FastJSON to 1.2.51.

pippo-server-parent/pippo-undertow/src/main/java/ro/pippo/undertow/websocket/UndertowWebSocketAdapter.java
… from connections list.
Undertow-specific Channel.addCloseTask method used to make sure the connection is always removed from the list.
Use readonly wrapper for connections passed to connection context.
fixes #484
=> Issue #484 - Use undertow channel tasks to remove closed/broken connections

pippo-server-parent/pippo-tomcat/pom.xml
=> update for tomcat

pippo-server-parent/pippo-jetty/pom.xml
=> update for jetty

.travis.yml
=> java 11 compatibility: travis build

pippo-core/src/main/java/ro/pippo/core/Response.java
Untested, but should work.
Fixes #519
=> Fix Character Encoding/Content-Length Bug in Response.commit(CharSequence)

pom.xml
Version 4.13 is currently the latest version of 4.x.
=> Update JUnit from 4.12 to 4.13

pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/ControllerRegistry.java, pippo-controller-parent/pippo-controller/src/test/java/ro/pippo/controller/ControllerRegistryTest.java
Fixes #525 
We faced this issue during upgrading from 1.7.0 to the latest Pippo version.
=> Handle non-empty Path and empty method path

pippo-core/src/main/java/ro/pippo/core/ContentTypeEngines.java
See note https://github.com/pippo-java/pippo/issues/537#issuecomment-636441015-permalink
=> ContentTypeEngines: Change the log level from debug to info

pippo-test/src/main/java/ro/pippo/test/PippoRule.java
=> PippoRule: Make methods public: startPippo and stopPippo

pippo-core/src/test/java/ro/pippo/core/route/PathTraversalResourceHandlerTest.java
=> Fix travis build failure

pippo-core/src/main/java/ro/pippo/core/AbstractWebServer.java, pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/PippoConstants.java, pippo-core/src/main/java/ro/pippo/core/WebServerSettings.java
=> Issue #586: Out of heap space for larger file uploads

pippo-core/src/main/java/ro/pippo/core/Application.java, pippo-core/src/main/java/ro/pippo/core/Request.java, pippo-core/src/main/java/ro/pippo/core/entity/DefaultEntityRequestEngine.java, pippo-core/src/main/java/ro/pippo/core/entity/EntityRequestEngine.java
Extract some methods from request to a new component.
The benefits:
- allow custom request to entity implementation
- decrees number of lines in `Request` (simplify code)
=> Add EntityRequestEngine

pippo-session-parent/pippo-session-jedis/pom.xml, pippo-session-parent/pippo-session-jedis/src/test/java/ro/pippo/session/jedis/JedisSessionDataStorageTest.java
=> Revert "Dynamically determine free port for Redis to listen on"

pippo-session-parent/pippo-session-jedis/pom.xml, pippo-session-parent/pippo-session-jedis/src/test/java/ro/pippo/session/jedis/JedisSessionDataStorageTest.java
As requested in https://github.com/pippo-java/pippo/pull/634#issuecomment-1431331039
=> Finish: Dynamically determine free port for Redis to listen on (#634)
